SELECT * FROM CONCERT_INFO;


INSERT INTO CONCERT_INFO (CONCERT_ID, TITLE, GENRE, RUNNING_TIME, CONCERT_DATE, LOCATION, TIME, HALL_ID)
SELECT 1, '예술의전당 여름음악축제', '클래식', 120, TO_DATE('2023-09-01', 'YYYY-MM-DD'), H.NAME, '19:00', 1
FROM HALL_INFO H
WHERE H.HALL_ID = 1;

INSERT INTO CONCERT_INFO (CONCERT_ID, TITLE, GENRE, RUNNING_TIME, CONCERT_DATE, LOCATION, TIME, HALL_ID)
SELECT 2, '조성진의 피아노 리사이틀', '클래식', 100, TO_DATE('2023-09-02', 'YYYY-MM-DD'), H.NAME, '19:30', 2
FROM HALL_INFO H
WHERE H.HALL_ID = 2;

INSERT INTO CONCERT_INFO (CONCERT_ID, TITLE, GENRE, RUNNING_TIME, CONCERT_DATE, LOCATION, TIME, HALL_ID)
SELECT 3, '유니버설발레단<돈키호테>', '발레', 90, TO_DATE('2023-09-03', 'YYYY-MM-DD'), H.NAME, '20:00', 3
FROM HALL_INFO H
WHERE H.HALL_ID = 3;

INSERT INTO CONCERT_INFO (CONCERT_ID, TITLE, GENRE, RUNNING_TIME, CONCERT_DATE, LOCATION, TIME, HALL_ID)
SELECT 4, 'BORN PINK WORLD TOUR', '케이팝', 120, TO_DATE('2023-09-08', 'YYYY-MM-DD'), H.NAME, '20:00', 4
FROM HALL_INFO H
WHERE H.HALL_ID = 4;

INSERT INTO CONCERT_INFO (CONCERT_ID, TITLE, GENRE, RUNNING_TIME, CONCERT_DATE, LOCATION, TIME, HALL_ID)
SELECT 5, 'Sam Smith', '팝', 70, TO_DATE('2023-09-09', 'YYYY-MM-DD'), H.NAME, '19:30', 4
FROM HALL_INFO H
WHERE H.HALL_ID = 4;

INSERT INTO CONCERT_INFO (CONCERT_ID, TITLE, GENRE, RUNNING_TIME, CONCERT_DATE, LOCATION, TIME, HALL_ID)
SELECT 6, 'Charlie Puth Live in Seoul', '팝', 120, TO_DATE('2023-09-10', 'YYYY-MM-DD'), H.NAME, '19:00', 4
FROM HALL_INFO H
WHERE H.HALL_ID = 4;

INSERT INTO CONCERT_INFO (CONCERT_ID, TITLE, GENRE, RUNNING_TIME, CONCERT_DATE, LOCATION, TIME, HALL_ID)
SELECT 7, 'Bruno Mars', '팝', 90, TO_DATE('2023-09-15', 'YYYY-MM-DD'), H.NAME, '20:00', 5
FROM HALL_INFO H
WHERE H.HALL_ID = 5;

INSERT INTO CONCERT_INFO (CONCERT_ID, TITLE, GENRE, RUNNING_TIME, CONCERT_DATE, LOCATION, TIME, HALL_ID)
SELECT 8, '김종욱 찾기', '뮤지컬', 100, TO_DATE('2023-09-16', 'YYYY-MM-DD'), H.NAME, '19:30', 6
FROM HALL_INFO H
WHERE H.HALL_ID = 6;

INSERT INTO CONCERT_INFO (CONCERT_ID, TITLE, GENRE, RUNNING_TIME, CONCERT_DATE, LOCATION, TIME, HALL_ID)
SELECT 9, 'Les Miserables', '뮤지컬', 150, TO_DATE('2023-09-16', 'YYYY-MM-DD'), H.NAME, '19:00', 7
FROM HALL_INFO H
WHERE H.HALL_ID = 7;

INSERT INTO CONCERT_INFO (CONCERT_ID, TITLE, GENRE, RUNNING_TIME, CONCERT_DATE, LOCATION, TIME, HALL_ID)
SELECT 10, 'MAMMA MIA!', '뮤지컬', 100, TO_DATE('2023-09-17', 'YYYY-MM-DD'), H.NAME, '19:30', 8
FROM HALL_INFO H
WHERE H.HALL_ID = 8;


DELETE FROM concert_info;